export const projectList = [
  {
    projectImage: '/projects/projectThumb.png',
    projectTitle: 'Carros Ferozes',
    projectDescription: 'Mobile development with React Native is an increasingly popular approach to creating high-quality mobile apps.',
    projectSiteLink: 'http://www.google.com',
    projectCodeLink: 'http://www.github.com',
    projectTech1: 'Node',
    projectTech2: 'React',
    projectTech3: 'Mongo',
    projectTech4: 'Tailwind',
    projectTech5: 'VueJs',
  },
  {
    projectImage: '/projects/projectThumb.png',
    projectTitle: 'Carros Ferozes 2',
    projectDescription: 'Mobile development with React Native is an increasingly popular approach to creating high-quality mobile apps.',
    projectSiteLink: 'http://www.google.com',
    projectCodeLink: 'http://www.github.com',
    projectTech1: 'Node',
    projectTech2: 'React',
    projectTech3: 'Tailwind',
    projectTech4: '',
    projectTech5: '',
  },
  {
    projectImage: '/projects/projectThumb.png',
    projectTitle: 'Carros Ferozes 3',
    projectDescription: 'Mobile development with React Native is an increasingly popular approach to creating high-quality mobile apps.',
    projectSiteLink: 'http://www.google.com',
    projectCodeLink: 'http://www.github.com',
    projectTech1: 'Node',
    projectTech2: '',
    projectTech3: '',
    projectTech4: '',
    projectTech5: '',
  },
  {
    projectImage: '/projects/projectThumb.png',
    projectTitle: 'Carros Ferozes 4',
    projectDescription: 'Mobile development with React Native is an increasingly popular approach to creating high-quality mobile apps.',
    projectSiteLink: 'http://www.google.com',
    projectCodeLink: 'http://www.github.com',
    projectTech1: 'Node',
    projectTech2: '',
    projectTech3: '',
    projectTech4: '',
    projectTech5: '',
  },
]